// PostPage domain constants.
// Values are shared by controller/view/utils and should remain stable unless
// post-detail behavior is explicitly changed.
export {
  NOTICE_BOARD_ID,
  ALL_BOARD_ID,
  COVER_FOR_BOARD_ID,
  WORK_SCHEDULE_BOARD_ID,
  WORK_SCHEDULE_BOARD_NAME,
  WORK_SCHEDULE_WRITE_ROLES,
  COVER_FOR_STATUS,
  COVER_FOR_DEFAULT_START_TIME,
  COVER_FOR_DEFAULT_END_TIME,
  DEFAULT_COVER_FOR_VENUE_OPTIONS,
  COVER_FOR_DEFAULT_VENUE,
  AUTO_LOGOUT_MESSAGE,
  LAST_BOARD_STORAGE_KEY,
  NOTIFICATION_TYPE,
  MENTION_ALL_TOKEN,
  MENTION_MAX_ITEMS,
  MENTION_MENU_ESTIMATED_WIDTH,
  MENTION_MENU_INITIAL,
  CORE_ROLE_LEVELS,
  ROLE_KEY_ALIASES,
  FALLBACK_ROLE_DEFINITIONS
} from '../shared/forum-constants.js';
import { BASE_NOTIFICATION_SUBTYPE } from '../shared/forum-constants.js';

export const NOTIFICATION_SUBTYPE = BASE_NOTIFICATION_SUBTYPE;
